const userOptions = {
  genders: ["Male", "Female", "Other", "Prefer not to say"],
  languages: ["Thai", "English", "Mandarin", "Lithuanian", "French", "Spanish", "German", "Hindi", "Arabic"],
  nationalities: ["Afghan", "Albanian", "Algerian", "Andorran", "Angolan",
  "Antiguan or Barbudan", "Argentine", "Armenian", "Australian", "Austrian",
  "Azerbaijani", "Bahamian", "Bahraini", "Bangladeshi", "Barbadian",
  "Belarusian", "Belgian", "Belizean", "Beninese", "Bhutanese",
  "Bolivian", "Bosnian or Herzegovinian", "Botswanan", "Brazilian", "Bruneian",
  "Bulgarian", "Burkinabé", "Burundian", "Cabo Verdean", "Cambodian",
  "Cameroonian", "Canadian", "Central African", "Chadian", "Chilean",
  "Chinese", "Colombian", "Comoran", "Congolese (Republic of the Congo)", "Costa Rican",
  "Croatian", "Cuban", "Cypriot", "Czech", "Congolese (DR Congo)",
  "Danish", "Djoutian", "Dominican (Dominican Republic)", "Dominican (Dominica)", "Ecuadorian",
  "Egyptian", "Salvadoran", "Equatoguinean", "Eritrean", "Estonian",
  "Swazi", "Ethiopian", "Fijian", "Finnish", "French",
  "Gabonese", "Gambian", "Georgian", "German", "Ghanaian",
  "Greek", "Grenadian", "Guatemalan", "Guinean", "Bissau-Guinean",
  "Guyanese", "Haitian", "Honduran", "Hungarian", "Icelandic",
  "Indian", "Indonesian", "Iranian", "Iraqi", "Irish",
  "Israeli", "Italian", "Jamaican", "Japanese", "Jordanian",
  "Kazakhstani", "Kenyan", "I-Kiribati", "Kuwaiti", "Kyrgyzstani",
  "Laotian", "Latvian", "Lebanese", "Lesotho", "Liberian",
  "Libyan", "Liechtensteiner", "Lithuanian", "Luxembourger", "Malagasy",
  "Malawian", "Malaysian", "Maldivian", "Malian", "Maltese",
  "Marshallese", "Mauritanian", "Mauritian", "Mexican", "Micronesian",
  "Moldovan", "Monegasque", "Mongolian", "Montenegrin", "Moroccan",
  "Mozambican", "Burmese", "Namibian", "Nauruan", "Nepali",
  "Dutch", "New Zealander", "Nicaraguan", "Nigerien", "Nigerian",
  "North Korean", "Macedonian", "Norwegian", "Omani", "Pakistani",
  "Palauan", "Palestinian", "Panamanian", "Papua New Guinean", "Paraguayan",
  "Peruvian", "Filipino", "Polish", "Portuguese", "Qatari",
  "Romanian", "Russian", "Rwandan", "Kittitian or Nevisian", "Saint Lucian",
  "Vincentian", "Samoan", "Sammarinese", "Sao Tomean", "Saudi",
  "Senegalese", "Serbian", "Seychellois", "Sierra Leonean", "Singaporean",
  "Slovak", "Slovenian", "Solomon Islander", "Somali", "South African",
  "South Korean", "South Sudanese", "Spanish", "Sri Lankan", "Sudanese",
  "Surinamese", "Swedish", "Swiss", "Syrian", "Taiwanese",
  "Tajik", "Tanzanian", "Thai", "Timorese", "Togolese",
  "Tongan", "Trinidadian or Tobagonian", "Tunisian", "Turkish", "Turkmen",
  "Tuvaluan", "Ugandan", "Ukrainian", "Emirati", "British",
  "American", "Uruguayan", "Uzbek", "Ni-Vanuatu", "Vatican",
  "Venezuelan", "Vietnamese", "Yemeni", "Zambian", "Zimbabwean"
],
  religions: [
    "Buddhism", "Christianity", "Hinduism", "Islam", "Judaism", "Other"
  ]
};

export default userOptions;